version: '3.8'

services:
  slime:
    build: .
    ports:
      - "${PORT:-8001}:${PORT:-8001}"  # API port
      - "3000:3000"  # Next.js port
    env_file:
      - .env
    environment:
      - PORT=${PORT:-8001}
      - NODE_ENV=production
      - SERVER_BASE_URL=http://localhost:${PORT:-8001}
    volumes:
      - ~/.adalflow:/root/.adalflow  # Persist repository and embedding data
